# Rolecraft - NO SETTINGS CAN BE CHANGED WITHOUT SERVER RESTART

# The SQL driver to use, must either be SQLite or MySQL
sqlserver: sqlite

# Only needed if you're using RolecraftAfterlife
originalsin: 1000

magicrange: 100

# Configuration for MySQL, can be ignored if using SQLite
mysql:
    username: 'user'
    password: 'password'
    address: 'localhost'
    databasename: 'rolecraft'
    port: 3306
