# Rolecraft - NO SETTINGS CAN BE CHANGED WITHOUT SERVER RESTART

# The SQL driver to use, must either be SQLite or MySQL
sqlserver: sqlite

# If a message isn't defined in the messages file, the value in the default
# localised file is used
default-locale: en-GB

# Only needed if you're using RolecraftAfterlife
originalsin: 1000

# The maximum range that spells have
magicrange: 100

# The maximum possible quantity of mana
maximummana: 2000

# The default constant used when determining mana regeneration rate, default 20
# Note that this is ignored if a specific constant is specified for a player's
# profession
manaregenconstant: 20

chatformat: "[channel] prefix <player> suffix: msg"

# Leaving this to true will enforce area protection and block protection
# plugins when players are casting spells, however this may cause problems
# with certain other plugins like NoCheatPlus that will report a cheater
# if blocks are broken from too far away, leave "true" unless you know 
# what you're doing
extraevents: true

# If a profession doesn't define a rule regarding a certain group, what
# should the default be?
professiondefaults:
    spells: true
    armor: true
    enchantments: true

# Whether to enable secondary professions, as well as options as to
# Which benefits of a profession should be granted to players who have
# selected the profession only as a secondary profession
# Secondary professions are disabled by default
secondprofessions:
    enabled: false
    spells: true
    armor: false
    items: true
    enchantments: true

# Teleport delay before teleporting to guild home, in seconds
teleportdelay: 4

# Configuration for MySQL, can be ignored if using SQLite
mysql:
    username: 'user'
    password: 'password'
    address: 'localhost'
    databasename: 'rolecraft'
    port: 3306
