name: RolecraftCore
version: '${plugin-version}'

description: Roleplaying plugin for Bukkit
authors: [PandazNWafflez, mythbusterma, TraksAG, LaughingQuoll]

main: com.github.rolecraftdev.RolecraftCore
softdepend: [Vault]

commands:
    guild:
        description: Guild-related commands
    profession:
        description: Profession-related commands
    gc:
        description: Switch between guild and normal chat, or send a one time guild chat message
        aliases: [guildchat, gchat]
    rcconfirm:
        description: Used for confirmation of sensitive actions
        aliases: [rconfirm]

permissions:
    rolecraft.guild.show:
        description: Allows viewing information about a guild
    rolecraft.guild.create:
        description: Allows usage of functionality related to guild administration, such as creating a guild
    rolecraft.guild.disband.other:
        description: Allows disbanding someone else's guild
    rolecraft.guild.home:
        description: Allows teleporting to the guild home
    rolecraft.profession.list:
        description: Allows viewing the profession list
    rolecraft.profession.use:
        description: Allows having a profession and using profession features
    rolecraft.spell.*:
        description: Access to all magical spells
        children:
          rolecraft.spell.fireball: true
    rolecraft.spell.fireball:
        description: Allows use of standard (non-exploding) fireballs
        default: true
